-- =====================================================
-- Liquidity Risk HOL - Data Setup
-- =====================================================
-- Creates all tables (DDL) and populates them with
-- realistic Basel III-compliant liquidity data (DML).
--
-- Run this AFTER creating your database and schemas.
-- Assumes: LIQUIDITY_RISK_DB exists with schemas
--          RAW, RAW_SANDBOX, PRESENTATION
-- =====================================================

USE DATABASE LIQUIDITY_RISK_DB;
USE SCHEMA RAW;

-- =====================================================
-- REFERENCE TABLES (DDL + DML)
-- =====================================================

-- 1. Asset Classifications (Basel III HQLA levels)
CREATE OR REPLACE TABLE ASSET_CLASSIFICATIONS (
    SECURITY_TYPE VARCHAR(50) PRIMARY KEY,
    HQLA_LEVEL VARCHAR(10) NOT NULL,
    HAIRCUT_PERCENT DECIMAL(5,2) NOT NULL,
    DESCRIPTION VARCHAR(500),
    REGULATORY_BASIS VARCHAR(200),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO ASSET_CLASSIFICATIONS (SECURITY_TYPE, HQLA_LEVEL, HAIRCUT_PERCENT, DESCRIPTION, REGULATORY_BASIS)
SELECT SECURITY_TYPE, HQLA_LEVEL, HAIRCUT_PERCENT, DESCRIPTION, REGULATORY_BASIS
FROM VALUES
    ('CASH', 'Level 1', 0.00, 'Cash and central bank reserves', 'Basel III Article 416'),
    ('CENTRAL_BANK_RESERVES', 'Level 1', 0.00, 'Central bank reserves', 'Basel III Article 416'),
    ('GOVERNMENT_BONDS_AAA', 'Level 1', 0.00, 'Government bonds rated AAA', 'Basel III Article 416'),
    ('GOVERNMENT_BONDS_AA', 'Level 1', 0.00, 'Government bonds rated AA', 'Basel III Article 416'),
    ('GOVERNMENT_BONDS_A', 'Level 1', 0.00, 'Government bonds rated A', 'Basel III Article 416'),
    ('CORPORATE_BONDS_AA', 'Level 2A', 15.00, 'Corporate bonds rated AA', 'Basel III Article 417'),
    ('COVERED_BONDS_AA', 'Level 2A', 15.00, 'Covered bonds rated AA', 'Basel III Article 417'),
    ('MUNICIPAL_BONDS_AA', 'Level 2A', 15.00, 'Municipal bonds rated AA', 'Basel III Article 417'),
    ('CORPORATE_BONDS_A', 'Level 2A', 15.00, 'Corporate bonds rated A', 'Basel III Article 417'),
    ('CORPORATE_BONDS_BBB', 'Level 2B', 25.00, 'Corporate bonds rated BBB', 'Basel III Article 418'),
    ('EQUITIES_MAIN_INDEX', 'Level 2B', 25.00, 'Equities included in main stock index', 'Basel III Article 418'),
    ('EQUITIES_OTHER', 'Level 2B', 50.00, 'Other equities', 'Basel III Article 418'),
    ('COVERED_BONDS_BBB', 'Level 2B', 25.00, 'Covered bonds rated BBB', 'Basel III Article 418')
AS v(SECURITY_TYPE, HQLA_LEVEL, HAIRCUT_PERCENT, DESCRIPTION, REGULATORY_BASIS);


-- 2. Business Unit Reference
CREATE OR REPLACE TABLE BUSINESS_UNIT_REFERENCE (
    BUSINESS_UNIT_ID VARCHAR(20) NOT NULL,
    BUSINESS_UNIT_NAME VARCHAR(100) NOT NULL,
    BUSINESS_UNIT_TYPE VARCHAR(50),
    REGION VARCHAR(50),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (BUSINESS_UNIT_ID)
);

INSERT INTO BUSINESS_UNIT_REFERENCE (BUSINESS_UNIT_ID, BUSINESS_UNIT_NAME, BUSINESS_UNIT_TYPE, REGION) VALUES
('GLOBAL', 'Global Bank', 'Group', 'Global'),
('US_TREASURY', 'US Treasury', 'Treasury', 'North America'),
('EU_TREASURY', 'EU Treasury', 'Treasury', 'Europe'),
('ASIA_TREASURY', 'Asia Treasury', 'Treasury', 'Asia'),
('US_TRADING', 'US Trading', 'Trading', 'North America'),
('EU_TRADING', 'EU Trading', 'Trading', 'Europe'),
('ASIA_TRADING', 'Asia Trading', 'Trading', 'Asia'),
('INVESTMENT_BANKING', 'Investment Banking', 'Investment Banking', 'Global'),
('WEALTH_MANAGEMENT', 'Wealth Management', 'Wealth Management', 'Global');


-- 3. Counterparty Data (2000 counterparties)
CREATE OR REPLACE TABLE COUNTERPARTY_DATA (
    COUNTERPARTY_ID VARCHAR(50) NOT NULL,
    COUNTERPARTY_NAME VARCHAR(200) NOT NULL,
    COUNTERPARTY_TYPE VARCHAR(50),
    CREDIT_RATING VARCHAR(10),
    REGION VARCHAR(50),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (COUNTERPARTY_ID)
);

INSERT INTO COUNTERPARTY_DATA (COUNTERPARTY_ID, COUNTERPARTY_NAME, COUNTERPARTY_TYPE, CREDIT_RATING, REGION)
SELECT 
    'CP_' || LPAD(SEQ8()::STRING, 6, '0') AS COUNTERPARTY_ID,
    'Counterparty ' || (SEQ8() + 1)::STRING AS COUNTERPARTY_NAME,
    CASE (SEQ8() % 4) WHEN 0 THEN 'Bank' WHEN 1 THEN 'Corporate' WHEN 2 THEN 'Sovereign' ELSE 'Institutional' END,
    CASE (SEQ8() % 5) WHEN 0 THEN 'AAA' WHEN 1 THEN 'AA' WHEN 2 THEN 'A' WHEN 3 THEN 'BBB' ELSE 'BB' END,
    CASE (SEQ8() % 3) WHEN 0 THEN 'North America' WHEN 1 THEN 'Europe' ELSE 'Asia' END
FROM TABLE(GENERATOR(ROWCOUNT => 2000));


-- 4. Currency Reference
CREATE OR REPLACE TABLE CURRENCY_REFERENCE (
    CURRENCY_CODE VARCHAR(3) PRIMARY KEY,
    CURRENCY_NAME VARCHAR(100) NOT NULL,
    IS_MAJOR_CURRENCY BOOLEAN DEFAULT FALSE,
    FX_RATE_USD DECIMAL(15,6),
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO CURRENCY_REFERENCE (CURRENCY_CODE, CURRENCY_NAME, IS_MAJOR_CURRENCY, FX_RATE_USD) VALUES
('USD', 'US Dollar', TRUE, 1.000000),
('EUR', 'Euro', TRUE, 0.920000),
('GBP', 'British Pound', TRUE, 0.790000),
('JPY', 'Japanese Yen', TRUE, 150.000000),
('CHF', 'Swiss Franc', TRUE, 0.880000),
('CAD', 'Canadian Dollar', TRUE, 1.350000),
('AUD', 'Australian Dollar', TRUE, 1.500000),
('CNY', 'Chinese Yuan', TRUE, 7.200000),
('HKD', 'Hong Kong Dollar', FALSE, 7.800000),
('SGD', 'Singapore Dollar', FALSE, 1.350000);


-- 5. Stress Scenarios
CREATE OR REPLACE TABLE STRESS_SCENARIOS (
    SCENARIO_ID VARCHAR(20) PRIMARY KEY,
    SCENARIO_NAME VARCHAR(100) NOT NULL,
    SCENARIO_TYPE VARCHAR(50),
    DESCRIPTION VARCHAR(500),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO STRESS_SCENARIOS (SCENARIO_ID, SCENARIO_NAME, SCENARIO_TYPE, DESCRIPTION) VALUES
('BASEL_STANDARD', 'Basel III Standard Scenario', 'Basel III', 'Standard Basel III stress scenario'),
('MARKET_CRISIS', 'Market Crisis Scenario', 'Custom', 'Severe market stress scenario'),
('LIQUIDITY_CRISIS', 'Liquidity Crisis Scenario', 'Custom', 'Extreme liquidity stress scenario');


-- 6. What-If Definitions Lookup (scenario parameters)
CREATE OR REPLACE TABLE WHAT_IF_DEFINITIONS_LOOKUP (
    WHAT_IF_ID VARCHAR(20),
    WHAT_IF_NAME VARCHAR(100) NOT NULL,
    REF_TBL VARCHAR(100) NOT NULL,
    TBL VARCHAR(100) NOT NULL,
    COL VARCHAR(100) NOT NULL,
    VAL VARCHAR(100) NOT NULL,
    FACTOR FLOAT NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO WHAT_IF_DEFINITIONS_LOOKUP (WHAT_IF_ID, WHAT_IF_NAME, REF_TBL, TBL, COL, VAL, FACTOR) VALUES
('1','Market Stress','COUNTERPARTY_DATA','COUNTERPARTY_DATA','REGION','Europe',-0.1),
('1','Market Stress','COUNTERPARTY_DATA','COUNTERPARTY_DATA','COUNTERPARTY_TYPE','Institutional',-0.15),
('1','Market Stress','POSITIONS','ASSET_CLASSIFICATIONS','SECURITY_TYPE','GOVERNMENT_BONDS_AAA',-0.05),
('1','Market Stress','POSITIONS','ASSET_CLASSIFICATIONS','SECURITY_TYPE','EQUITIES_MAIN_INDEX',-0.1),
('1','Market Stress','POSITIONS','BUSINESS_UNIT_REFERENCE','BUSINESS_UNIT_TYPE','Treasury',-0.05),
('1','Market Stress','CASH_INFLOWS','BUSINESS_UNIT_REFERENCE','BUSINESS_UNIT_TYPE','Treasury',-0.02),
('1','Market Stress','CASH_INFLOWS','BUSINESS_UNIT_REFERENCE','REGION','North America',-0.1),
('1','Market Stress','CASH_OUTFLOWS','BUSINESS_UNIT_REFERENCE','BUSINESS_UNIT_TYPE','Treasury',-0.01),
('1','Market Stress','CASH_OUTFLOWS','BUSINESS_UNIT_REFERENCE','REGION','North America',-0.05),
('2','Asia Outflow Spike','COUNTERPARTY_DATA','COUNTERPARTY_DATA','REGION','Europe',-0.1),
('2','Asia Outflow Spike','COUNTERPARTY_DATA','COUNTERPARTY_DATA','REGION','Asia',-0.15),
('2','Asia Outflow Spike','COUNTERPARTY_DATA','COUNTERPARTY_DATA','COUNTERPARTY_TYPE','Institutional',-0.15),
('2','Asia Outflow Spike','COUNTERPARTY_DATA','COUNTERPARTY_DATA','COUNTERPARTY_TYPE','Bank',-0.05),
('2','Asia Outflow Spike','POSITIONS','ASSET_CLASSIFICATIONS','SECURITY_TYPE','GOVERNMENT_BONDS_AAA',-0.05),
('2','Asia Outflow Spike','POSITIONS','ASSET_CLASSIFICATIONS','SECURITY_TYPE','EQUITIES_MAIN_INDEX',-0.1),
('2','Asia Outflow Spike','POSITIONS','BUSINESS_UNIT_REFERENCE','BUSINESS_UNIT_TYPE','Treasury',-0.05),
('2','Asia Outflow Spike','CASH_INFLOWS','BUSINESS_UNIT_REFERENCE','BUSINESS_UNIT_TYPE','Investment Banking',-0.02),
('2','Asia Outflow Spike','CASH_INFLOWS','BUSINESS_UNIT_REFERENCE','BUSINESS_UNIT_TYPE','Trading',-0.1),
('2','Asia Outflow Spike','CASH_INFLOWS','BUSINESS_UNIT_REFERENCE','REGION','Europe',-0.2),
('2','Asia Outflow Spike','CASH_OUTFLOWS','BUSINESS_UNIT_REFERENCE','BUSINESS_UNIT_TYPE','Trading',-0.01),
('2','Asia Outflow Spike','CASH_OUTFLOWS','BUSINESS_UNIT_REFERENCE','REGION','Europe',-0.05);


-- =====================================================
-- FACT TABLES (DDL + DML)
-- =====================================================

-- Market Data (price history for position valuation)
CREATE OR REPLACE TABLE MARKET_DATA (
    SECURITY_ID VARCHAR(50) NOT NULL,
    SECURITY_TYPE VARCHAR(50),
    PRICE_USD NUMBER(20,4),
    MARKET_DATE DATE NOT NULL,
    CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SECURITY_ID)
);

INSERT INTO MARKET_DATA (SECURITY_ID, SECURITY_TYPE, PRICE_USD, MARKET_DATE)
WITH MARKET_DATA_REFERENCE AS (
    SELECT 
        'SEC_' || LPAD((SEQ8())::STRING, 6, '0') AS SECURITY_ID,
        CASE (SEQ8() % 8)
            WHEN 0 THEN 'GOVERNMENT_BONDS_AAA' WHEN 1 THEN 'GOVERNMENT_BONDS_AA' WHEN 2 THEN 'GOVERNMENT_BONDS_A'
            WHEN 3 THEN 'CORPORATE_BONDS_AA' WHEN 4 THEN 'CORPORATE_BONDS_A' WHEN 5 THEN 'EQUITIES_MAIN_INDEX'
            WHEN 6 THEN 'CORPORATE_BONDS_BBB' ELSE 'COVERED_BONDS_AA'
        END AS SECURITY_TYPE,
        100.00 + (UNIFORM(0::FLOAT, 1::FLOAT, RANDOM()) * 900)::DECIMAL(20,4) AS PRICE_USD,
        CURRENT_DATE() AS MARKET_DATE
    FROM TABLE(GENERATOR(ROWCOUNT => 10000))
)
SELECT B.SECURITY_ID, B.SECURITY_TYPE, B.PRICE_USD * UNIFORM(.98, 1.0199, RANDOM()) AS PRICE_USD, 
       CURRENT_DATE() - A.DAY AS MARKET_DATE
FROM (SELECT SEQ8() AS DAY FROM TABLE(GENERATOR(ROWCOUNT => 365))) a
     JOIN MARKET_DATA_REFERENCE b
ORDER BY SECURITY_ID, MARKET_DATE;


-- Positions (500K+ rows with market-derived valuations)
CREATE OR REPLACE TABLE POSITIONS (
    POSITION_ID VARCHAR(50) NOT NULL,
    BUSINESS_UNIT_ID VARCHAR(20) NOT NULL,
    SECURITY_ID VARCHAR(50) NOT NULL,
    SECURITY_TYPE VARCHAR(50) NOT NULL,
    POSITION_TYPE VARCHAR(20) NOT NULL,
    QUANTITY NUMBER(20,4) NOT NULL,
    POSITION_VALUE_USD NUMBER(20,2) NOT NULL,
    POSITION_DATE DATE NOT NULL,
    MATURITY_DATE DATE,
    CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (POSITION_ID)
);

INSERT INTO POSITIONS (POSITION_ID, BUSINESS_UNIT_ID, SECURITY_ID, SECURITY_TYPE, POSITION_TYPE, QUANTITY, 
                       POSITION_VALUE_USD, POSITION_DATE, MATURITY_DATE)
WITH POSITION_REFERENCE AS (
    SELECT 
        'POS_' || LPAD(SEQ8()::STRING, 8, '0') AS POSITION_ID,
        CASE (SEQ8() % 9)
            WHEN 0 THEN 'US_TRADING' WHEN 1 THEN 'US_TREASURY' WHEN 2 THEN 'EU_TRADING'
            WHEN 3 THEN 'EU_TREASURY' WHEN 4 THEN 'ASIA_TRADING' WHEN 5 THEN 'ASIA_TREASURY'
            WHEN 6 THEN 'GLOBAL' WHEN 7 THEN 'INVESTMENT_BANKING' ELSE 'WEALTH_MANAGEMENT'
        END AS BUSINESS_UNIT_ID,
        'SEC_' || LPAD((SEQ8() % 10000)::STRING, 6, '0') AS SECURITY_ID,
        CASE (SEQ8() % 2) WHEN 0 THEN 'Long' ELSE 'Short' END AS POSITION_TYPE,
        (1 + UNIFORM(1, 5.01::FLOAT, RANDOM()) * 99)::DECIMAL(20,4) AS QUANTITY,
        (100000 + UNIFORM(0::FLOAT, 1::FLOAT, RANDOM()) * 9900000)::DECIMAL(20,2) AS MARKET_VALUE_USD,
        CURRENT_DATE() - (SEQ8() % 365) AS POSITION_DATE,
        CASE (SEQ8() % 3)
            WHEN 0 THEN NULL
            ELSE CURRENT_DATE() + (SEQ8() % 730)
        END AS MATURITY_DATE
    FROM TABLE(GENERATOR(ROWCOUNT => 500000))
)
SELECT a.POSITION_ID, a.BUSINESS_UNIT_ID, a.SECURITY_ID, b.SECURITY_TYPE, a.POSITION_TYPE, 
       a.QUANTITY, a.QUANTITY * b.PRICE_USD as POSITION_VALUE_USD, a.POSITION_DATE, a.MATURITY_DATE
FROM POSITION_REFERENCE a
JOIN MARKET_DATA b ON a.SECURITY_ID = b.SECURITY_ID AND a.POSITION_DATE = b.MARKET_DATE
UNION
SELECT 'POS_' || LPAD((SEQ8()+500000)::STRING, 8, '0'),
       CASE (SEQ8() % 9)
           WHEN 0 THEN 'US_TRADING' WHEN 1 THEN 'US_TREASURY' WHEN 2 THEN 'EU_TRADING'
           WHEN 3 THEN 'EU_TREASURY' WHEN 4 THEN 'ASIA_TRADING' WHEN 5 THEN 'ASIA_TREASURY'
           WHEN 6 THEN 'GLOBAL' WHEN 7 THEN 'INVESTMENT_BANKING' ELSE 'WEALTH_MANAGEMENT'
       END,
       'CASH_' || LPAD((SEQ8())::STRING, 6, '0'),
       CASE (SEQ8() % 2) WHEN 0 THEN 'CASH' ELSE 'CENTRAL_BANK_RESERVES' END,
       'Long', 1, (10000 + (UNIFORM(0::FLOAT, 1::FLOAT, RANDOM()) * 9900000))::DECIMAL(20,2),
       CURRENT_DATE() - (SEQ8() % 365), NULL
FROM TABLE(GENERATOR(ROWCOUNT => 80000));


-- Cash Inflows (100K rows)
CREATE OR REPLACE TABLE CASH_INFLOWS (
    INFLOW_ID VARCHAR(50) NOT NULL,
    BUSINESS_UNIT_ID VARCHAR(20) NOT NULL,
    COUNTERPARTY_ID VARCHAR(50) NOT NULL,
    INFLOW_TYPE VARCHAR(50) NOT NULL,
    INFLOW_AMOUNT_USD NUMBER(20,2) NOT NULL,
    MATURITY_DATE DATE,
    POSITION_DATE DATE NOT NULL,
    CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (INFLOW_ID)
);

INSERT INTO CASH_INFLOWS (INFLOW_ID, BUSINESS_UNIT_ID, COUNTERPARTY_ID, INFLOW_TYPE, INFLOW_AMOUNT_USD, MATURITY_DATE, POSITION_DATE)
SELECT 
    'INFLOW_' || LPAD(SEQ8()::STRING, 8, '0'),
    CASE (SEQ8() % 9)
        WHEN 0 THEN 'US_TRADING' WHEN 1 THEN 'US_TREASURY' WHEN 2 THEN 'EU_TRADING'
        WHEN 3 THEN 'EU_TREASURY' WHEN 4 THEN 'ASIA_TRADING' WHEN 5 THEN 'ASIA_TREASURY'
        WHEN 6 THEN 'GLOBAL' WHEN 7 THEN 'INVESTMENT_BANKING' ELSE 'WEALTH_MANAGEMENT'
    END,
    'CP_' || LPAD((SEQ8() % 2000)::STRING, 6, '0'),
    CASE (SEQ8() % 4) WHEN 0 THEN 'DEPOSIT' WHEN 1 THEN 'LOAN_REPAYMENT' WHEN 2 THEN 'INTEREST_PAYMENT' ELSE 'OTHER' END,
    (1000000 + UNIFORM(0::FLOAT, 1::FLOAT, RANDOM()) * 990000000)::DECIMAL(20,2) / UNIFORM(1200, 1600, RANDOM()),
    CASE 
        WHEN (SEQ8() % 10) = 0 THEN NULL
        WHEN (SEQ8() % 10) < 4 THEN CURRENT_DATE() + (SEQ8() % 90)
        WHEN (SEQ8() % 10) < 7 THEN CURRENT_DATE() + 90 + (SEQ8() % 90)
        WHEN (SEQ8() % 10) < 9 THEN CURRENT_DATE() + 180 + (SEQ8() % 185)
        ELSE CURRENT_DATE() + 365 + (SEQ8() % 365)
    END,
    CURRENT_DATE() - (SEQ8() % 365)
FROM TABLE(GENERATOR(ROWCOUNT => 100000));


-- Cash Outflows (100K rows)
CREATE OR REPLACE TABLE CASH_OUTFLOWS (
    OUTFLOW_ID VARCHAR(50) NOT NULL,
    BUSINESS_UNIT_ID VARCHAR(20) NOT NULL,
    COUNTERPARTY_ID VARCHAR(50) NOT NULL,
    OUTFLOW_TYPE VARCHAR(50) NOT NULL,
    OUTFLOW_AMOUNT_USD NUMBER(20,2) NOT NULL,
    MATURITY_DATE DATE,
    POSITION_DATE DATE NOT NULL,
    CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (OUTFLOW_ID)
);

INSERT INTO CASH_OUTFLOWS (OUTFLOW_ID, BUSINESS_UNIT_ID, COUNTERPARTY_ID, OUTFLOW_TYPE, OUTFLOW_AMOUNT_USD, MATURITY_DATE, POSITION_DATE)
SELECT 
    'OUTFLOW_' || LPAD(SEQ8()::STRING, 8, '0'),
    CASE (SEQ8() % 9)
        WHEN 0 THEN 'US_TRADING' WHEN 1 THEN 'US_TREASURY' WHEN 2 THEN 'EU_TRADING'
        WHEN 3 THEN 'EU_TREASURY' WHEN 4 THEN 'ASIA_TRADING' WHEN 5 THEN 'ASIA_TREASURY'
        WHEN 6 THEN 'GLOBAL' WHEN 7 THEN 'INVESTMENT_BANKING' ELSE 'WEALTH_MANAGEMENT'
    END,
    'CP_' || LPAD((SEQ8() % 2000)::STRING, 6, '0'),
    CASE (SEQ8() % 4) WHEN 0 THEN 'DEPOSIT' WHEN 1 THEN 'LOAN_REPAYMENT' WHEN 2 THEN 'INTEREST_PAYMENT' ELSE 'OTHER' END,
    (1000000 + UNIFORM(0::FLOAT, 1::FLOAT, RANDOM()) * 990000000)::DECIMAL(20,2) / UNIFORM(1200, 1600, RANDOM()),
    CASE 
        WHEN (SEQ8() % 10) = 0 THEN NULL
        WHEN (SEQ8() % 10) < 4 THEN CURRENT_DATE() + (SEQ8() % 90)
        WHEN (SEQ8() % 10) < 7 THEN CURRENT_DATE() + 90 + (SEQ8() % 90)
        WHEN (SEQ8() % 10) < 9 THEN CURRENT_DATE() + 180 + (SEQ8() % 185)
        ELSE CURRENT_DATE() + 365 + (SEQ8() % 365)
    END,
    CURRENT_DATE() - (SEQ8() % 365)
FROM TABLE(GENERATOR(ROWCOUNT => 100000));


-- HQLA Summary/Detail (transient working tables)
CREATE OR REPLACE TRANSIENT TABLE HQLA_SUMMARY (
    DAY_NUMBER NUMBER(38,0),
    TOTAL_HQLA_USD NUMBER(38,2)
);

CREATE OR REPLACE TRANSIENT TABLE HQLA_DETAIL (
    MATURITY_DATE DATE,
    TOTAL_HQLA_USD NUMBER(32,10)
);


-- =====================================================
-- SANDBOX TABLES (Clones for what-if isolation)
-- =====================================================
USE SCHEMA RAW_SANDBOX;

CREATE OR REPLACE TABLE POSITIONS CLONE LIQUIDITY_RISK_DB.RAW.POSITIONS;
CREATE OR REPLACE TABLE CASH_INFLOWS CLONE LIQUIDITY_RISK_DB.RAW.CASH_INFLOWS;
CREATE OR REPLACE TABLE CASH_OUTFLOWS CLONE LIQUIDITY_RISK_DB.RAW.CASH_OUTFLOWS;
CREATE OR REPLACE TABLE COUNTERPARTY_DATA CLONE LIQUIDITY_RISK_DB.RAW.COUNTERPARTY_DATA;
CREATE OR REPLACE TABLE BUSINESS_UNIT_REFERENCE CLONE LIQUIDITY_RISK_DB.RAW.BUSINESS_UNIT_REFERENCE;
CREATE OR REPLACE TABLE ASSET_CLASSIFICATIONS CLONE LIQUIDITY_RISK_DB.RAW.ASSET_CLASSIFICATIONS;
CREATE OR REPLACE TABLE WHAT_IF_DEFINITIONS_LOOKUP CLONE LIQUIDITY_RISK_DB.RAW.WHAT_IF_DEFINITIONS_LOOKUP;
CREATE OR REPLACE TRANSIENT TABLE HQLA_SUMMARY CLONE LIQUIDITY_RISK_DB.RAW.HQLA_SUMMARY;
CREATE OR REPLACE TRANSIENT TABLE HQLA_DETAIL CLONE LIQUIDITY_RISK_DB.RAW.HQLA_DETAIL;


-- =====================================================
-- PRESENTATION TABLES (empty, populated by notebooks)
-- =====================================================
USE SCHEMA PRESENTATION;

CREATE OR REPLACE TABLE LCR (
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    DAY_NUMBER NUMBER(38,0),
    TOTAL_NET_CASH_OUTFLOWS NUMBER(38,2),
    HQLA NUMBER(38,10),
    LCR NUMBER(38,12)
);

CREATE OR REPLACE TABLE WHAT_IF_LCR (
    WHAT_IF_ID VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    DAY_NUMBER NUMBER(38,0),
    TOTAL_NET_CASH_OUTFLOWS NUMBER(38,2),
    HQLA NUMBER(38,10),
    LCR NUMBER(38,12)
);
